# Generated by Django 3.0 on 2020-11-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateField(default='2020-11-24')),
                ('due_date', models.DateField(default='2020-11-24')),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
