# Generated by Django 3.0 on 2020-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201124_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2020-11-25'),
        ),
    ]
