# Generated by Django 3.0 on 2020-11-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20201126_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Check',
            new_name='check',
        ),
    ]
