# Generated by Django 3.0 on 2020-11-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20201126_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='check',
            field=models.CharField(default='Yes/No', max_length=20),
        ),
    ]
